services:
  # Backend API Service
  - type: web
    name: blablaship-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: blablaship-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://your-frontend-domain.vercel.app

databases:
  # PostgreSQL Database
  - name: blablaship-db
    plan: free